# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('nota_debito', 'Nota de Débito'), ('nota_credito', 'Nota de Crédito')], default='factura', max_length=20)),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('numero_control', models.CharField(help_text='Número de control fiscal', max_length=50, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible_reducida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible_suntuaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('iva_general_pct', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('iva_reducida_pct', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('iva_suntuaria_pct', models.DecimalField(decimal_places=2, default=Decimal('31.00'), max_digits=5)),
                ('monto_iva_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_iva_reducida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_iva_suntuaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igtf_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('monto_igtf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuesto a Grandes Transacciones Financieras', max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('anulada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='ventas.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_impuesto', models.CharField(choices=[('exento', 'Exento'), ('general', 'General (16%)'), ('reducida', 'Reducida (8%)'), ('suntuaria', 'Suntuaria (31%)')], default='general', max_length=20)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.productoventa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.facturaventa')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Facturas',
            },
        ),
        migrations.CreateModel(
            name='RetencionISLR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(max_length=20, unique=True, verbose_name='Número de Comprobante')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('nro_factura', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('fecha_factura', models.DateField(verbose_name='Fecha de Factura')),
                ('codigo_concepto', models.CharField(help_text='Ej: 001 para Honorarios Profesionales', max_length=10)),
                ('monto_operacion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Imponible')),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Retención')),
                ('sustraendo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto en Bs. a restar del cálculo', max_digits=15)),
                ('monto_retenido', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('periodo_fiscal', models.CharField(help_text='AAAAMM', max_length=6)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_islr', to='facturacion.proveedor')),
            ],
            options={
                'verbose_name': 'Retención de ISLR',
                'verbose_name_plural': 'Retenciones de ISLR',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='RetencionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(help_text='Formato: AAAAMMDDDDDDDD', max_length=14, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('nro_factura', models.CharField(max_length=50)),
                ('nro_control', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('tipo_transaccion', models.CharField(default='01', help_text='01-Registro, 02-Nota Debito, 03-Nota Credito', max_length=2)),
                ('monto_total_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5)),
                ('monto_retenido', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('periodo_fiscal', models.CharField(help_text='Formato: AAAAMM', max_length=6)),
                ('anulada', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_iva', to='facturacion.proveedor')),
            ],
            options={
                'verbose_name': 'Retención de IVA',
                'verbose_name_plural': 'Retenciones de IVA',
                'ordering': ['-fecha_emision', '-nro_comprobante'],
            },
        ),
    ]
