# Generated by Django 6.0.8 on 2026-09-14 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0019_muestraprenda_aprobacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_trabajo', models.CharField(blank=True, max_length=50)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('procedimiento', models.CharField(choices=[('corte', '01 - Verificación en proceso y despacho de corte'), ('arranque', '02 - Aprobación de prenda de arranque'), ('costura', '03 - Verificación en proceso de línea de costura'), ('prenda_terminada', '04 - Inspección final de prenda terminada'), ('bordado', '05 - Inspección de bordado y auditoría de remate'), ('empaque', '06 - Verificación final de prendas empacadas'), ('materia_prima', '07 - Verificación de avíos y telas')], max_length=25)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('aprobado_observacion', 'Aprobado con observación'), ('rechazado', 'Rechazado'), ('reproceso', 'En reproceso'), ('cerrado', 'Cerrado')], default='borrador', max_length=25)),
                ('fecha_inspeccion', models.DateField()),
                ('galpon', models.CharField(blank=True, max_length=80)),
                ('linea_costura', models.CharField(blank=True, max_length=80)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(blank=True, max_length=80)),
                ('talla', models.CharField(blank=True, max_length=50)),
                ('descripcion_prenda', models.CharField(blank=True, max_length=255)),
                ('ficha_tecnica_referencia', models.CharField(blank=True, max_length=255)),
                ('muestra_referencia', models.CharField(blank=True, max_length=255)),
                ('ficha_arte_referencia', models.CharField(blank=True, max_length=255)),
                ('cantidad_lote', models.PositiveIntegerField(default=0)),
                ('cantidad_muestra', models.PositiveIntegerField(default=0)),
                ('piezas_aprobadas', models.PositiveIntegerField(default=0)),
                ('piezas_rechazadas', models.PositiveIntegerField(default=0)),
                ('defectos_criticos', models.PositiveIntegerField(default=0)),
                ('defectos_mayores', models.PositiveIntegerField(default=0)),
                ('defectos_menores', models.PositiveIntegerField(default=0)),
                ('operaciones_revisadas', models.PositiveIntegerField(default=0)),
                ('piezas_por_operacion', models.PositiveIntegerField(default=0)),
                ('rollos_revisados', models.PositiveIntegerField(default=0)),
                ('conos_revisados', models.PositiveIntegerField(default=0)),
                ('medidas_registradas', models.TextField(blank=True)),
                ('controles_realizados', models.TextField()),
                ('defectos_observaciones', models.TextField(blank=True)),
                ('prueba_solidez_realizada', models.BooleanField(default=False)),
                ('tiempo_reposo_verificado', models.BooleanField(default=False)),
                ('ancho_util_verificado', models.BooleanField(default=False)),
                ('simetria_verificada', models.BooleanField(default=False)),
                ('remate_verificado', models.BooleanField(default=False)),
                ('empaque_verificado', models.BooleanField(default=False)),
                ('decision_observaciones', models.TextField(blank=True)),
                ('requiere_reproceso', models.BooleanField(default=False)),
                ('notificado_a', models.CharField(blank=True, max_length=255)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_calidad_realizadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_calidad', to='produccion.ordenproduccion')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_calidad_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_calidad_validadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_inspeccion', '-creado_en'),
            },
        ),
    ]
