# Generated by Django 6.0.8 on 2026-09-15 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_empleado_bono_alimentacion_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalOAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_oac', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='JornadaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('fecha', models.DateField()),
                ('especialidad', models.CharField(max_length=120)),
                ('lugar', models.CharField(max_length=150)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('atendidos', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('convocada', 'Convocada'), ('ejecutada', 'Ejecutada'), ('cancelada', 'Cancelada')], default='planificada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jornadas', to='oac.personaloac')),
            ],
        ),
        migrations.CreateModel(
            name='CitaCiudadana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('ciudadano', models.CharField(max_length=180)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField()),
                ('fecha_cita', models.DateTimeField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada')], default='solicitada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='oac.personaloac')),
            ],
        ),
        migrations.CreateModel(
            name='BusquedaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.CharField(max_length=180)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('medicamento', models.CharField(max_length=180)),
                ('presentacion', models.CharField(blank=True, max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_busqueda', 'En búsqueda'), ('encontrada', 'Encontrada'), ('no_disponible', 'No disponible'), ('cerrada', 'Cerrada')], default='recibida', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='busquedas_medicamentos', to='oac.personaloac')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoOAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField()),
                ('partida', models.CharField(max_length=120)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='oac.personaloac')),
            ],
            options={
                'ordering': ('-ejercicio', 'partida'),
                'unique_together': {('ejercicio', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiario', models.CharField(max_length=180)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='solicitada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones', to='oac.personaloac')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donaciones', to='oac.presupuestooac')),
            ],
        ),
    ]
