# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True, verbose_name='Año Fiscal')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ejercicio Fiscal',
                'verbose_name_plural': 'Ejercicios Fiscales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de la cuenta según VEN-NIF', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('C', 'Capital / Patrimonio'), ('I', 'Ingreso'), ('E', 'Egreso / Gasto')], max_length=1)),
                ('permite_movimientos', models.BooleanField(default=True, help_text='False si es una cuenta agrupadora')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('asentado', 'Asentado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ejercicio_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.ejerciciofiscal')),
            ],
            options={
                'verbose_name': 'Comprobante de Diario',
                'verbose_name_plural': 'Comprobantes de Diario',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LineaComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.comprobantediario')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Línea de Comprobante',
                'verbose_name_plural': 'Líneas de Comprobantes',
            },
        ),
    ]
