# Generated by Django 6.0.8 on 2026-09-15 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_empleado_bono_alimentacion_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=150)),
                ('registro_profesional', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_medico', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AfectacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('restricciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_seguimiento', 'En seguimiento'), ('cerrada', 'Cerrada')], default='abierta', max_length=15)),
                ('confidencial', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones_salud', to='rrhh.empleado')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones', to='servicios_medicos.personalmedico')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField()),
                ('partida', models.CharField(max_length=120)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='servicios_medicos.personalmedico')),
            ],
            options={
                'unique_together': {('ejercicio', 'partida')},
            },
        ),
        migrations.CreateModel(
            name='EquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('marca_modelo', models.CharField(blank=True, max_length=150)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(max_length=150)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('asignado', 'Asignado'), ('mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado'), ('baja', 'Dado de baja')], default='operativo', max_length=15)),
                ('valor_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('custodio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='servicios_medicos.personalmedico')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='servicios_medicos.presupuestomedico')),
            ],
        ),
        migrations.CreateModel(
            name='ReposoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('diagnostico', models.TextField()),
                ('soporte', models.FileField(blank=True, upload_to='medico/reposos/%Y/%m/')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('validado', 'Validado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado')], default='solicitado', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reposos_medicos', to='rrhh.empleado')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reposos_validados', to='servicios_medicos.personalmedico')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo_examen', models.CharField(max_length=150)),
                ('resultado', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('apto', 'Apto'), ('no_apto', 'No apto'), ('observado', 'Observado')], default='pendiente', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ingreso', to='rrhh.empleado')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_ingreso', to='servicios_medicos.personalmedico')),
            ],
        ),
    ]
