@echo off
TITLE ERP Limpieza - Servidor de Desarrollo
echo Cargando configuracion del ERP...
cd /d "C:\Users\Administrator\Documents\Proyecto\ERPSIMPLE\erp_limpieza"
set PYTHONPATH=%CD%
echo Activando entorno virtual (env)...
call .\env\Scripts\activate
echo Aplicando migraciones de base de datos...
python manage.py migrate
echo Recolectando archivos estaticos...
python manage.py collectstatic --noinput
echo Iniciando servidor Django...
python manage.py runserver
pause