@echo off
TITLE ERP Produccion Textil - Servidor de Desarrollo
echo Cargando configuracion del ERP...
cd /d "%~dp0"
set PYTHONPATH=%CD%
echo Activando entorno virtual (.venv)...
call .\.venv\Scripts\activate
echo Aplicando migraciones de base de datos...
python manage.py migrate
echo Iniciando servidor Django...
python manage.py runserver
pause