# Generated by Django 6.0.4 on 2026-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=20, verbose_name='RIF / NIT')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('moneda_simbolo', models.CharField(default='$', max_length=5)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
        migrations.CreateModel(
            name='RegistroRespaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('tamano_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Respaldo',
                'verbose_name_plural': 'Registros de Respaldos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
