# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorespaldo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorespaldo',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
