# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida'), ('T', 'Transferencia')], max_length=1)),
                ('motivo', models.CharField(choices=[('compra', 'Recepción de Compra'), ('produccion', 'Producción de Lote'), ('consumo', 'Consumo en Producción'), ('venta', 'Despacho de Venta'), ('ajuste', 'Ajuste de Inventario'), ('transferencia', 'Transferencia entre Almacenes')], default='ajuste', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, help_text='Ej: Consumo OP-123, Compra OC-45', max_length=100, null=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='logistica.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='logistica.almacen')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='produccion.materiaprima')),
                ('producto_pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='produccion.productoterminado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_logistica', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExistenciaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='logistica.almacen')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.materiaprima')),
                ('producto_pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produccion.productoterminado')),
            ],
            options={
                'unique_together': {('almacen', 'materia_prima'), ('almacen', 'producto_pt')},
            },
        ),
    ]
