# Generated by Django 6.0.4 on 2026-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Recepción de Compra'), ('produccion', 'Producción de Lote / Rollo'), ('consumo', 'Consumo en Planta Textil'), ('venta', 'Despacho de Venta'), ('ajuste', 'Ajuste de Inventario'), ('transferencia', 'Transferencia entre Almacenes')], default='ajuste', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ej: Consumo OP-123, Lote Hilo #45', max_length=100, null=True),
        ),
    ]
