# Generated by Django 6.0.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_alter_movimientoinventario_motivo_and_more'),
        ('produccion', '0008_seed_produccion_textil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('aguja', 'Agujas'), ('cuchilla', 'Cuchillas'), ('correa', 'Correas'), ('motor', 'Motores'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('maquina_compatible', models.CharField(blank=True, max_length=150)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='existenciaalmacen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo',
            field=models.CharField(choices=[('repuestos', 'Repuestos de máquinas de confección'), ('materias_primas', 'Telas e hilos'), ('consumibles', 'Consumibles textiles'), ('producto_terminado', 'Producto terminado'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='produccion.materiaprima'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='produccion.productoterminado'),
        ),
        migrations.AddField(
            model_name='existenciaalmacen',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.repuestomaquina'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='logistica.repuestomaquina'),
        ),
        migrations.AddConstraint(
            model_name='existenciaalmacen',
            constraint=models.UniqueConstraint(fields=('almacen', 'materia_prima'), name='unique_existencia_materia_prima'),
        ),
        migrations.AddConstraint(
            model_name='existenciaalmacen',
            constraint=models.UniqueConstraint(fields=('almacen', 'producto_pt'), name='unique_existencia_producto'),
        ),
        migrations.AddConstraint(
            model_name='existenciaalmacen',
            constraint=models.UniqueConstraint(fields=('almacen', 'repuesto'), name='unique_existencia_repuesto'),
        ),
        migrations.AddConstraint(
            model_name='existenciaalmacen',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('producto_pt__isnull', True), ('repuesto__isnull', True)), models.Q(('materia_prima__isnull', True), ('producto_pt__isnull', False), ('repuesto__isnull', True)), models.Q(('materia_prima__isnull', True), ('producto_pt__isnull', True), ('repuesto__isnull', False)), _connector='OR'), name='existencia_un_solo_item'),
        ),
    ]
