# Generated by Django 6.0.8 on 2026-09-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_detalleordencompra_moneda_facturacompra_moneda_and_more'),
        ('logistica', '0004_seed_almacenes_textiles'),
        ('produccion', '0019_muestraprenda_aprobacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('atendida', 'Atendida'), ('anulada', 'Anulada')], default='borrador', max_length=15)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=15)),
                ('detalle_materiales', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_abastecimiento', to='logistica.almacen')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_logistica', to='produccion.ordenproduccion')),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_logistica', to='compras.requerimientomaterial')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_abastecimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=40, unique=True)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('documento_referencia', models.CharField(blank=True, max_length=100)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calidad_verificada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conforme', 'Conforme'), ('observada', 'Observada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_logistica', to='logistica.almacen')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_logistica', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='logistica.solicitudabastecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DespachoLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('destino', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('observado', 'Observado')], default='preparando', max_length=15)),
                ('detalle_materiales', models.TextField()),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recibido_por', models.CharField(blank=True, max_length=150)),
                ('documento_entrega', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_logistica', to='logistica.almacen')),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_logistica', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='logistica.solicitudabastecimiento')),
            ],
        ),
    ]
