# Generated by Django 6.0.8 on 2026-09-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_empleado_bono_alimentacion_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('clausula', models.CharField(blank=True, max_length=80)),
                ('organismo', models.CharField(default='ISO', max_length=150)),
                ('version', models.CharField(default='2015', max_length=40)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaCalidadISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('alcance', models.TextField()),
                ('resultado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_ejecucion', 'En ejecución'), ('cerrada', 'Cerrada')], default='planificada', max_length=15)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_iso', to='rrhh.empleado')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='gerencia_calidad.normacalidad')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('periodo', models.CharField(max_length=30)),
                ('unidad', models.CharField(max_length=40)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores_calidad', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('objetivo', models.TextField()),
                ('entradas', models.TextField(blank=True)),
                ('salidas', models.TextField(blank=True)),
                ('indicadores', models.TextField(blank=True)),
                ('riesgos', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procesos_calidad', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('mayor', 'Mayor'), ('menor', 'Menor'), ('observacion', 'Observación')], max_length=12)),
                ('requisito', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('causa', models.TextField(blank=True)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('accion', 'En acción'), ('verificada', 'Verificada'), ('cerrada', 'Cerrada')], default='abierta', max_length=12)),
                ('auditoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='gerencia_calidad.auditoriacalidadiso')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='rrhh.empleado')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_conformidades', to='gerencia_calidad.procesocalidad')),
            ],
        ),
        migrations.AddField(
            model_name='auditoriacalidadiso',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='gerencia_calidad.procesocalidad'),
        ),
    ]
