# Generated by Django 6.0.8 on 2026-09-15 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioPresupuestario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('moneda', models.CharField(default='VES', max_length=3)),
                ('monto_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('formulacion', 'En formulación'), ('aprobado', 'Aprobado'), ('ejecucion', 'En ejecución'), ('cerrado', 'Cerrado')], default='formulacion', max_length=12)),
                ('instrumento_aprobacion', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.CharField(default='Venezuela', max_length=80)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('organismo', models.CharField(blank=True, max_length=180)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('version_vigente', models.CharField(blank=True, max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=220)),
                ('periodo_desde', models.PositiveIntegerField()),
                ('periodo_hasta', models.PositiveIntegerField()),
                ('objetivos', models.TextField()),
                ('indicadores', models.TextField(blank=True)),
                ('responsable', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('vigente', 'Vigente'), ('cerrado', 'Cerrado')], default='borrador', max_length=12)),
                ('documento', models.FileField(blank=True, upload_to='planificacion/planes/%Y/')),
            ],
        ),
        migrations.CreateModel(
            name='ModificacionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('credito_adicional', 'Crédito adicional'), ('traspaso', 'Traspaso'), ('rectificacion', 'Rectificación'), ('reduccion', 'Reducción')], max_length=20)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('aplicada', 'Aplicada')], default='solicitada', max_length=12)),
                ('instrumento', models.CharField(blank=True, max_length=150)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modificaciones', to='planificacion_presupuesto.ejerciciopresupuestario')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=180)),
                ('responsable', models.CharField(max_length=180)),
                ('objetivo', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='planificacion_presupuesto.ejerciciopresupuestario')),
            ],
            options={
                'unique_together': {('ejercicio', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ObjetivoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
                ('linea_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=180)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_institucionales', to='planificacion_presupuesto.planestrategico')),
            ],
            options={
                'unique_together': {('plan', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40)),
                ('denominacion', models.CharField(max_length=220)),
                ('asignado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('causado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fuente_financiamiento', models.CharField(blank=True, max_length=150)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='planificacion_presupuesto.ejerciciopresupuestario')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='planificacion_presupuesto.unidadpresupuestaria')),
            ],
            options={
                'unique_together': {('ejercicio', 'codigo', 'unidad')},
            },
        ),
    ]
