# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Q1', 'Primera Quincena'), ('Q2', 'Segunda Quincena'), ('MEN', 'Mensual'), ('VAC', 'Vacaciones'), ('UTI', 'Utilidades (Aguinaldos)'), ('LIQ', 'Liquidación')], default='Q1', max_length=3, verbose_name='Tipo de Nómina')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes correspondiente')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=1.0, max_digits=14, verbose_name='Tasa BCV aplicable')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('total_asignaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Asignaciones')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Deducciones')),
                ('total_nomina', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Neto a Pagar')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROCESADA', 'Procesada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Cargo')),
                ('nivel', models.CharField(choices=[('profesional', 'Nivel Profesional y Técnico'), ('supervision', 'Nivel de Supervisión y Dirección'), ('estrategico', 'Niveles Estratégicos y Gerenciales'), ('operativo', 'Niveles Operativos y Especialistas')], default='operativo', max_length=20, verbose_name='Nivel Jerárquico')),
                ('sector', models.CharField(choices=[('publico', 'Sector Público (A.P.N)'), ('privado', 'Sector Privado'), ('mixto', 'Mixto / General')], default='privado', max_length=20, verbose_name='Sector de Referencia')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Funciones')),
                ('salario_base_referencial', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Base Ref.')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='rrhh.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero')], default='V', max_length=1, verbose_name='Nacionalidad')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula de Identidad')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección de Habitación')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Números de Contacto')),
                ('grado_instruccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grado de Instrucción')),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Sangre')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('estatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Estatura (m)')),
                ('enfermedades', models.TextField(blank=True, null=True, verbose_name='Enfermedades Preexistentes')),
                ('discapacidad', models.TextField(blank=True, null=True, verbose_name='Discapacidades (Si aplica)')),
                ('talla_camisa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla de Camisa')),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla de Pantalón')),
                ('talla_calzado', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla de Calzado')),
                ('tipo_contrato', models.CharField(choices=[('IND', 'Tiempo Indeterminado'), ('DET', 'Tiempo Determinado'), ('OBR', 'Por Obra Determinada')], default='IND', max_length=3, verbose_name='Tipo de Contrato')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Base (VES)')),
                ('bono_alimentacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Cesta Ticket / Bono Alimentación (VES)')),
                ('bono_divisas', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bono Complementario (USD)')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso')),
                ('cargas_familiares', models.IntegerField(default=0, verbose_name='Cargas Familiares')),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Bancaria (20 dígitos)')),
                ('activo', models.BooleanField(default=True, verbose_name='Empleado Activo')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rrhh.cargo', verbose_name='Cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CestaTicketRecibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('dias_trabajados', models.IntegerField(default=30, verbose_name='Días Laborados')),
                ('monto_mensual_ley', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto Cestaticket')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto a Pagar')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('PAGADO', 'Pagado')], default='GENERADO', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Recibo de Cestaticket',
                'verbose_name_plural': 'Recibos de Cestaticket',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_egreso', models.DateField(verbose_name='Fecha de Egreso')),
                ('motivo_egreso', models.CharField(choices=[('RENUNCIA', 'Renuncia Voluntaria'), ('DESPIDO_J', 'Despido Justificado'), ('DESPIDO_I', 'Despido Injustificado')], default='RENUNCIA', max_length=50)),
                ('salario_integral_diario', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Integral Diario')),
                ('prestaciones_acumuladas', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Fideicomiso Acumulado')),
                ('vacaciones_fraccionadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Vacaciones Fraccionadas')),
                ('bono_vacacional_fraccionado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bono Vacacional Fraccionado')),
                ('utilidades_fraccionadas', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Utilidades Fraccionadas')),
                ('indemnizacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Indemnización (Art. 92)')),
                ('total_liquidacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Liquidación')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
        migrations.CreateModel(
            name='NominaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Sueldo Base')),
                ('bono_alimentacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Cesta Ticket')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Horas Extras')),
                ('bono_produccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bonos / Otros Ingresos')),
                ('ivss', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Retención IVSS (4%)')),
                ('faov', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Retención FAOV (1%)')),
                ('paro_forzoso', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Retención SPF (0.5%)')),
                ('inces', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Retención INCES (0.5%)')),
                ('otras_deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Otras Deducciones')),
                ('total_asignaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Asignaciones')),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Deducciones')),
                ('neto_recibir', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Neto a Recibir')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rrhh.nomina', verbose_name='Nómina')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
            },
        ),
        migrations.CreateModel(
            name='PrestacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(help_text='Ej: 2024-Q1', max_length=10, verbose_name='Trimestre')),
                ('salario_integral_diario', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Integral Diario')),
                ('dias_abonados', models.IntegerField(default=15, verbose_name='Días Abonados (Art. 142)')),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto Abonado')),
                ('anticipos', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Anticipos')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Prestación Social',
                'verbose_name_plural': 'Prestaciones Sociales',
            },
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año Fiscal')),
                ('dias_utilidad', models.IntegerField(default=30, verbose_name='Días de Utilidades (Min 30)')),
                ('salario_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Promedio')),
                ('monto_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Monto Utilidades')),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Utilidad (Aguinaldo)',
                'verbose_name_plural': 'Utilidades',
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('dias_disfrute', models.IntegerField(default=15, verbose_name='Días Hábiles de Disfrute')),
                ('bono_vacacional_dias', models.IntegerField(default=15, verbose_name='Días de Bono Vacacional (Art. 192)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('DISFRUTADA', 'Disfrutada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
