# Generated by Django 6.0.8 on 2026-09-12 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_empleado_estado_alter_empleado_activo'),
        ('tesoreria', '0002_movimientotesoreria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='banco_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados_pago', to='tesoreria.banco'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_cuenta_pago',
            field=models.CharField(blank=True, default='corriente', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cedula', 'Cédula'), ('rif', 'RIF'), ('partida_nacimiento', 'Partida de nacimiento'), ('estudios', 'Estudios'), ('cv', 'CV personal'), ('constancia_medica', 'Constancia médica')], max_length=30)),
                ('archivo', models.FileField(max_length=255, upload_to='rrhh/documentos/%Y/%m/')),
                ('numero', models.CharField(blank=True, max_length=60)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('validado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rrhh.empleado')),
            ],
        ),
    ]
