# Generated by Django 6.0.3 on 2026-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_seed_cargos_textiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='bono_alimentacion_moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='VES', max_length=3, verbose_name='Moneda de cesta ticket'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bono_divisas_moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda del bono complementario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bono_guerra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bono de Guerra Económica'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bono_guerra_moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='VES', max_length=3, verbose_name='Moneda del bono de guerra'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bono_produccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bono de Producción'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='bono_produccion_moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='VES', max_length=3, verbose_name='Moneda del bono de producción'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='VES', max_length=3, verbose_name='Moneda del salario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='bono_alimentacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Cesta Ticket'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='bono_divisas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Bono Complementario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario Base'),
        ),
    ]
