# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Nro. guia de despacho')),
                ('numero_control', models.CharField(blank=True, max_length=30, verbose_name='Nro. de control')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('rif_emisor', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Use el formato RIF venezolano: J-12345678-9.', regex='^[JGVEP]-\\d{8}-\\d$')])),
                ('razon_social_emisor', models.CharField(max_length=200)),
                ('rif_receptor', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Use el formato RIF venezolano: J-12345678-9.', regex='^[JGVEP]-\\d{8}-\\d$')])),
                ('razon_social_receptor', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('transportista_nombre', models.CharField(max_length=200)),
                ('transportista_rif', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Use el formato RIF venezolano: J-12345678-9.', regex='^[JGVEP]-\\d{8}-\\d$')])),
                ('vehiculo_placa', models.CharField(max_length=20)),
                ('conductor_nombre', models.CharField(max_length=150)),
                ('conductor_cedula', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Use el formato de cedula: V-12345678 o E-12345678.', regex='^[VE]-\\d{6,9}$')])),
                ('licencia_grado', models.CharField(blank=True, max_length=30)),
                ('tipo_carga', models.CharField(max_length=120)),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unidad_peso', models.CharField(default='kg', max_length=20)),
                ('clase_embalaje', models.CharField(blank=True, max_length=120)),
                ('sin_derecho_credito_fiscal', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Guia de despacho',
                'verbose_name_plural': 'Guias de despacho',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('motivo', models.CharField(choices=[('compra', 'Recepcion de compra'), ('venta', 'Despacho por venta'), ('traslado_guia', 'Traslado con guia de despacho'), ('devolucion', 'Devolucion'), ('consumo', 'Consumo interno o produccion'), ('merma', 'Merma o deterioro'), ('ajuste_fiscal', 'Ajuste documentado')], default='ajuste_fiscal', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento_tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_DESPACHO', 'Guia de despacho'), ('NOTA_ENTREGA', 'Nota de entrega'), ('ACTA_AJUSTE', 'Acta de ajuste'), ('ORDEN_PRODUCCION', 'Orden de produccion')], default='ACTA_AJUSTE', max_length=20)),
                ('documento_numero', models.CharField(help_text='Ej: FAC-000123, GD-000045 o REC-2026-0001', max_length=100)),
                ('numero_control', models.CharField(blank=True, max_length=30, verbose_name='Nro. de control fiscal')),
                ('referencia', models.CharField(blank=True, help_text='Referencia interna del ERP', max_length=100)),
                ('lote', models.CharField(blank=True, max_length=60)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Tasa BCV')),
                ('observaciones', models.TextField(blank=True)),
                ('guia_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventarios.guiadespacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='compras.productocompra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['producto', 'fecha'], name='inventarios_product_7dbaa3_idx'), models.Index(fields=['documento_tipo', 'documento_numero'], name='inventarios_documen_adb449_idx'), models.Index(fields=['lote'], name='inventarios_lote_d58e0b_idx')],
            },
        ),
    ]
