# Generated by Django 6.0.8 on 2026-09-15 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.CharField(default='Venezuela', max_length=80)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('organismo', models.CharField(blank=True, max_length=180)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('version_vigente', models.CharField(blank=True, max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=220)),
                ('domicilio', models.CharField(blank=True, max_length=250)),
                ('contacto', models.CharField(blank=True, max_length=180)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('registro_proveedores', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inhabilitado', 'Inhabilitado'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('documentos_vigentes', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='ProcesoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('objeto', models.CharField(max_length=250)),
                ('justificacion', models.TextField()),
                ('unidad_solicitante', models.CharField(max_length=180)),
                ('modalidad', models.CharField(choices=[('concurso_abierto', 'Concurso abierto'), ('consulta_precios', 'Consulta de precios'), ('contratacion_directa', 'Contratación directa'), ('contratacion_excluida', 'Contratación excluida')], max_length=25)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('publicado', 'Publicado'), ('evaluacion', 'En evaluación'), ('adjudicado', 'Adjudicado'), ('contratado', 'Contratado'), ('ejecucion', 'En ejecución'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='planificado', max_length=15)),
                ('presupuesto_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=180)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_contratacion_aprobados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_inicio', '-numero'),
            },
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('plazo_dias', models.PositiveIntegerField(default=0)),
                ('puntaje_tecnico', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('puntaje_economico', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('evaluada', 'Evaluada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='recibida', max_length=12)),
                ('documento', models.FileField(blank=True, upload_to='contrataciones/ofertas/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='contrataciones_publicas.procesocontratacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='contrataciones_publicas.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('comite_o_responsable', models.CharField(max_length=220)),
                ('metodologia', models.TextField()),
                ('acta_numero', models.CharField(blank=True, max_length=60)),
                ('decision', models.TextField()),
                ('documento', models.FileField(blank=True, upload_to='contrataciones/evaluaciones/%Y/%m/')),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='contrataciones_publicas.procesocontratacion')),
                ('proveedor_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contrataciones_publicas.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('objeto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('supervisor', models.CharField(max_length=180)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('suspendido', 'Suspendido'), ('terminado', 'Terminado'), ('rescindido', 'Rescindido')], default='borrador', max_length=12)),
                ('documento', models.FileField(blank=True, upload_to='contrataciones/contratos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contrataciones_publicas.procesocontratacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contrataciones_publicas.proveedor')),
            ],
        ),
    ]
