# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use RIF venezolano. Ej: J-12345678-9.', regex='^[JGVEP]-?\\d{7,9}-?\\d?$')])),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('contador_nombre', models.CharField(blank=True, max_length=150)),
                ('contador_cpc', models.CharField(blank=True, max_length=50)),
                ('contador_rif', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use RIF venezolano. Ej: J-12345678-9.', regex='^[JGVEP]-?\\d{7,9}-?\\d?$')])),
                ('gerente_nombre', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rif', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use RIF venezolano. Ej: J-12345678-9.', regex='^[JGVEP]-?\\d{7,9}-?\\d?$')])),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cedula')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.area')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('naturaleza', models.CharField(max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('es_cuenta_mayor', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='core.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ejerciciocontable')),
            ],
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='RetencionIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_comprobante', models.CharField(help_text='Formato: AAAAMMDDDDDDDD', max_length=14, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('nro_factura', models.CharField(max_length=50)),
                ('nro_control', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('tipo_transaccion', models.CharField(default='01', max_length=2)),
                ('monto_total_compra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5)),
                ('monto_retenido', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('periodo_fiscal', models.CharField(blank=True, max_length=6)),
                ('anulada', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retenciones_iva', to='core.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.CharField(default='LECTURA_ESCRITURA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, related_name='roles', to='core.area')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.rol'),
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.ejerciciocontable')),
            ],
            options={
                'unique_together': {('ejercicio', 'mes', 'anio')},
            },
        ),
    ]
