# Generated by Django 6.0.3 on 2026-09-12 16:14

from django.db import migrations, models


def crear_monedas(apps, schema_editor):
    Moneda = apps.get_model('core', 'Moneda')
    Moneda.objects.bulk_create([
        Moneda(codigo='VES', nombre='Bolívar venezolano', simbolo='Bs.', es_base=True),
        Moneda(codigo='USD', nombre='Dólar estadounidense', simbolo='$'),
        Moneda(codigo='EUR', nombre='Euro', simbolo='€'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('VES', 'Bolívar venezolano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro')], max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('simbolo', models.CharField(max_length=5)),
                ('es_base', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('usd_ves', models.DecimalField(decimal_places=6, max_digits=18)),
                ('eur_ves', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuente', models.CharField(default='Banco Central de Venezuela', max_length=120)),
                ('publicada_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RunPython(crear_monedas, migrations.RunPython.noop),
    ]
