# Generated by Django 6.0.3 on 2026-09-12 16:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moneda_tasabcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasabcv',
            name='eur_ves',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='tasabcv',
            name='usd_ves',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
