# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_sudeban', models.CharField(blank=True, max_length=4)),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código/Sudeban')),
                ('pais', models.CharField(default='Venezuela', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_ruc', models.CharField(blank=True, max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('proveedor_ruc', models.CharField(blank=True, max_length=20)),
                ('concepto', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Pago Parcial'), ('pagada', 'Pagada')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_asignado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('activa', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro')], default='corriente', max_length=10)),
                ('moneda', models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares')], default='VES', max_length=3)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('titular', models.CharField(blank=True, max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesoreria.banco')),
            ],
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('medio_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('pago_movil', 'Pago Móvil')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.cuentabancaria')),
                ('cxc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='tesoreria.cuentaporcobrar')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tesoreria.caja')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto Total Factura')),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto transado', max_digits=20)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto Base Imponible')),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto IVA')),
                ('porcentaje_retencion', models.DecimalField(choices=[(Decimal('0.00'), 'Sin Retención'), (Decimal('75.00'), '75% (General)'), (Decimal('100.00'), '100% (Casos Especiales)')], decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('monto_retenido', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20)),
                ('medio_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('pago_movil', 'Pago Móvil')], default='transferencia', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.cuentabancaria')),
                ('cxp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tesoreria.cuentaporpagar')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('pago', 'Pago'), ('cobro', 'Cobro'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste')], default='ajuste', max_length=20)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_igtf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto retenido por IGTF (si aplica)', max_digits=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('conciliado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tesoreria.cuentabancaria')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='tesoreria.pago')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('ejecutada', models.BooleanField(default=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='tesoreria.cuentabancaria')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_realizadas', to='tesoreria.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('anio', models.IntegerField()),
                ('saldo_estado_cuenta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo final en el estado de cuenta del banco', max_digits=20)),
                ('saldo_libros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo final en el sistema', max_digits=20)),
                ('fecha_cierre', models.DateField()),
                ('cerrada', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='tesoreria.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Conciliación Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'unique_together': {('cuenta', 'mes', 'anio')},
            },
        ),
    ]
