# Generated by Django 6.0.3 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_movimientotesoreria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='VES', max_length=3),
        ),
    ]
