# Generated by Django 6.0.8 on 2026-09-15 15:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('computador', 'Computador'), ('servidor', 'Servidor'), ('red', 'Equipo de red'), ('impresora', 'Impresora'), ('telefonia', 'Telefonía'), ('otro', 'Otro')], max_length=15)),
                ('nombre', models.CharField(max_length=150)),
                ('marca_modelo', models.CharField(blank=True, max_length=150)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('custodio', models.CharField(blank=True, max_length=180)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('garantia_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('asignado', 'Asignado'), ('mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado'), ('baja', 'Dado de baja')], default='operativo', max_length=15)),
                ('valor_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=120)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones')], default='activo', max_length=12)),
                ('supervisor', models.CharField(blank=True, max_length=180)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Personal de tecnología',
                'verbose_name_plural': 'Personal de tecnología',
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.CreateModel(
            name='MonitoreoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicio_o_enlace', models.CharField(max_length=180)),
                ('segmento', models.CharField(blank=True, max_length=120)),
                ('direccion', models.GenericIPAddressField(blank=True, null=True)),
                ('latencia_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('disponibilidad', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('degradado', 'Degradado'), ('caido', 'Caído'), ('mantenimiento', 'Mantenimiento')], default='operativo', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoreos', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=12)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('programado', 'Programado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='tecnologia_informacion.equipoti')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('periodo', models.CharField(max_length=30)),
                ('unidad', models.CharField(max_length=40)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('actividad', models.CharField(max_length=180)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada'), ('no_realizada', 'No realizada')], default='planificada', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='tecnologia_informacion.personalti')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='PlanModernizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('alcance', models.TextField()),
                ('justificacion', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado'), ('detenido', 'Detenido')], default='propuesto', max_length=15)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modernizaciones', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTrabajoTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('cerrado', 'Cerrado')], default='borrador', max_length=15)),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_trabajo', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('proveedor', models.CharField(blank=True, max_length=180)),
                ('documento_compra', models.CharField(blank=True, max_length=80)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('conforme', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='tecnologia_informacion.equipoti')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('ambiente', models.CharField(default='Producción', max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('apagado', 'Apagado'), ('mantenimiento', 'Mantenimiento'), ('retirado', 'Retirado')], default='activo', max_length=15)),
                ('criticidad', models.CharField(default='media', max_length=20)),
                ('dependencia', models.CharField(blank=True, max_length=180)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.CharField(max_length=180)),
                ('area', models.CharField(max_length=150)),
                ('equipo_requerido', models.CharField(max_length=180)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('evaluacion', 'En evaluación'), ('aprobada', 'Aprobada'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='solicitada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_aprobadas', to='tecnologia_informacion.personalti')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.CharField(max_length=180)),
                ('area_solicitante', models.CharField(blank=True, max_length=150)),
                ('asunto', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(default='Soporte', max_length=100)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('asignado', 'Asignado'), ('en_atencion', 'En atención'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='abierto', max_length=15)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tecnologia_informacion.personalti')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
