# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Materias Primas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Productos Terminados',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('rendimiento', models.DecimalField(decimal_places=2, help_text='Cantidad producida por lote', max_digits=10)),
                ('unidad_rendimiento', models.CharField(default='unidades', max_length=20)),
                ('procedimiento', models.TextField(blank=True, help_text='Pasos detallados de mezclado y seguridad (EPI)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('obsoleta', 'Obsoleta')], default='borrador', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU/Código')),
                ('concentracion', models.DecimalField(decimal_places=2, default=100.0, help_text='Pureza o Concentración %', max_digits=5)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('lt', 'Litros'), ('un', 'Unidades'), ('gr', 'Gramos'), ('ml', 'Mililitros')], max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.categoriamateriaprima')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_empaque', models.BooleanField(default=False, help_text='Marcar si es envase, tapa o etiqueta')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='produccion.formula')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_numero', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nro de Lote Asignado')),
                ('cantidad_a_producir', models.PositiveIntegerField(default=1, help_text='Número de veces la fórmula')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='planificada', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fecha_planificada', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('costo_total_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.formula')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH')),
                ('viscosidad', models.DecimalField(blank=True, decimal_places=2, help_text='en cP (centipoise)', max_digits=10, null=True)),
                ('densidad', models.DecimalField(blank=True, decimal_places=3, help_text='en g/cm³', max_digits=6, null=True)),
                ('concentracion_activo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% Ingrediente Activo')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('olor', models.CharField(blank=True, max_length=50)),
                ('aspecto', models.CharField(blank=True, help_text='Ej: Líquido traslúcido, Gel, etc.', max_length=100)),
                ('cumple_covenin', models.BooleanField(default=False, verbose_name='Cumple Normas COVENIN')),
                ('estabilidad_alcalina', models.BooleanField(default=True, verbose_name='Estabilidad Química')),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('inspector', models.CharField(max_length=100)),
                ('orden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_calidad', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Control de Calidad',
                'verbose_name_plural': 'Controles de Calidad',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('presentacion', models.CharField(choices=[('1L', 'Envase 1 Litro'), ('3.78L', 'Galón 3.78 Litros'), ('5L', 'Envase 5 Litros'), ('10L', 'Envase 10 Litros'), ('20L', 'Bidón 20 Litros'), ('200L', 'Tambor 200 Litros')], default='1L', max_length=10)),
                ('registro_sanitario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro Registro Sanitario / CPE')),
                ('normativa_covenin', models.CharField(blank=True, help_text='Norma COVENIN aplicable', max_length=100, null=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.categoriaproductoterminado')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.productoterminado'),
        ),
    ]
