# Generated by Django 6.0.4 on 2026-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcalidad',
            options={'verbose_name': 'Control de Calidad Textil', 'verbose_name_plural': 'Controles de Calidad Textil'},
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='aspecto',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='concentracion_activo',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='cumple_covenin',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='densidad',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='estabilidad_alcalina',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='olor',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='controlcalidad',
            name='viscosidad',
        ),
        migrations.RemoveField(
            model_name='lineaformula',
            name='es_empaque',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='normativa_covenin',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='registro_sanitario',
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='ancho_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='defectos_por_100m',
            field=models.IntegerField(default=0, help_text='Sistema de penalización de puntos'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='gramaje_real',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='g/m2', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='tono_color',
            field=models.CharField(blank=True, help_text='Validación visual en caja de luz', max_length=50),
        ),
        migrations.AddField(
            model_name='lineaformula',
            name='es_insumo_auxiliar',
            field=models.BooleanField(default=False, help_text='Marcar si es tinte, químico o accesorio menor'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='composicion',
            field=models.CharField(default='100% Algodón', help_text='Ej: 100% Algodón, Poliéster/Spandex', max_length=100),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='gramaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='g/m2', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='procedimiento',
            field=models.TextField(blank=True, help_text='Instrucciones de tejeduría, tensión y teñido'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='rendimiento',
            field=models.DecimalField(decimal_places=2, help_text='Metros o unidades producidas por lote', max_digits=10),
        ),
        migrations.AlterField(
            model_name='formula',
            name='unidad_rendimiento',
            field=models.CharField(default='metros', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('m', 'Metros lineales'), ('cono', 'Conos de hilo'), ('lts', 'Litros (Tintes/Químicos)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_a_producir',
            field=models.PositiveIntegerField(default=1, help_text='Escala de producción'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='lote_numero',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Partida / Nro de Lote'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='presentacion',
            field=models.CharField(choices=[('rollo', 'Rollo de Tela'), ('pieza', 'Pieza'), ('prenda', 'Prenda Terminada')], default='rollo', max_length=20),
        ),
    ]
