# Generated by Django 6.0.4 on 2026-09-06 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_controlcalidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='lineaformula',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='lineaformula',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='materiaprima',
            name='composicion',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='costo_total_real',
        ),
        migrations.RemoveField(
            model_name='productoterminado',
            name='presentacion',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='piezas_producidas_ok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='piezas_realizadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='piezas_rechazadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='produccion.productoterminado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoterminado',
            name='tipo_prenda',
            field=models.CharField(choices=[('deportivo', 'Uniforme Deportivo'), ('militar_gala', 'Uniforme Militar de Gala'), ('militar_tropa', 'Uniforme Militar de Tropa'), ('institucional', 'Ropa Institucional'), ('otro', 'Otro')], default='institucional', max_length=30),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materiaprima',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('m', 'Metros lineales'), ('cono', 'Conos de hilo'), ('lts', 'Litros (Tintes/Químicos)')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_a_producir',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de piezas requeridas'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('planificada', 'Planificada (UDP)'), ('en_corte', 'En Corte'), ('en_bordado', 'En Bordados'), ('en_produccion', 'En Confección / Producción'), ('en_despacho', 'En Despacho / Empaque'), ('en_calidad', 'Control de Calidad ISO 9001'), ('completada', 'Completada y Notificada'), ('anulada', 'Anulada')], default='planificada', max_length=25),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='lote_numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Lote / Orden ID'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.categoriaproductoterminado'),
        ),
        migrations.CreateModel(
            name='DepartamentoBordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_bordado', models.CharField(help_text='Ej: Escudo Militar, Logo Institucional, Nombre', max_length=200)),
                ('piezas_bordadas_ok', models.PositiveIntegerField(default=0)),
                ('piezas_rechazadas_bordado', models.PositiveIntegerField(default=0)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bordados', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoCalidadISO9001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumple_iso_9001', models.BooleanField(default=False, help_text='Certifica cumplimiento de normas ISO 9001')),
                ('gramaje_verificado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('piezas_aprobadas_qc', models.PositiveIntegerField(default=0)),
                ('piezas_rechazadas_qc', models.PositiveIntegerField(default=0)),
                ('informe_auditoria', models.TextField(help_text='Detalles del dictamen de calidad y observaciones directivas')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_iso', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_tela_utilizados', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('piezas_cortadas', models.PositiveIntegerField(default=0)),
                ('piezas_defectuosas_corte', models.PositiveIntegerField(default=0)),
                ('fecha_corte', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('operario_corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corte', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planchado_ok', models.BooleanField(default=False)),
                ('empaquetado_ok', models.BooleanField(default=False)),
                ('piezas_empaquetadas', models.PositiveIntegerField(default=0)),
                ('fecha_empaque', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='produccion.ordenproduccion')),
                ('responsable_empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piezas_ensambladas', models.PositiveIntegerField(default=0)),
                ('piezas_con_falla_costura', models.PositiveIntegerField(default=0)),
                ('fecha_ensamble', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('jefe_linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produccion_confeccion', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoUDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_diseño', models.CharField(blank=True, help_text='Ruta o link del diseño digital / Plotter', max_length=255)),
                ('especificaciones', models.TextField(help_text='Detalles para Uniformes Militares, de Gala, Institucionales o Deportivos')),
                ('impresion_plotter_ok', models.BooleanField(default=False, help_text='Verificado impresión en Pronted/Plotter')),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('diseñador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='udp', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.DeleteModel(
            name='ControlCalidad',
        ),
        migrations.DeleteModel(
            name='Formula',
        ),
        migrations.DeleteModel(
            name='LineaFormula',
        ),
    ]
