# Generated by Django 6.0.4 on 2026-09-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_remove_formula_producto_remove_lineaformula_formula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamentocorte',
            old_name='piezas_cortadas',
            new_name='disenos_recibidos',
        ),
        migrations.RenameField(
            model_name='departamentocorte',
            old_name='metros_tela_utilizados',
            new_name='tela_tendida_metros',
        ),
        migrations.RenameField(
            model_name='departamentoudp',
            old_name='fecha_aprobacion',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='departamentocorte',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='departamentocorte',
            name='operario_corte',
        ),
        migrations.RemoveField(
            model_name='departamentoudp',
            name='archivo_diseño',
        ),
        migrations.RemoveField(
            model_name='departamentoudp',
            name='diseñador',
        ),
        migrations.RemoveField(
            model_name='departamentoudp',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='departamentoudp',
            name='impresion_plotter_ok',
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='piezas_por_lote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='cantidad_disenos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='piezas_por_diseno',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='proyecto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='tipo_diseno',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='tipo_tela',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='departamentocorte',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corte_list', to='produccion.ordenproduccion'),
        ),
        migrations.AlterField(
            model_name='departamentoudp',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='udp_list', to='produccion.ordenproduccion'),
        ),
        migrations.CreateModel(
            name='DepartamentoProduccionTextil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_produccion', models.CharField(blank=True, max_length=100, null=True)),
                ('productos_realizados', models.PositiveIntegerField(default=0)),
                ('piezas_con_falla_costura', models.PositiveIntegerField(default=0)),
                ('fecha_produccion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produccion_textil_list', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.DeleteModel(
            name='DepartamentoProduccion',
        ),
    ]
