# Generated by Django 6.0.4 on 2026-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_rename_piezas_cortadas_departamentocorte_disenos_recibidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentoudp',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
