# Generated by Django 6.0.8 on 2026-09-12 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_departamentoudp_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('departamento', models.CharField(choices=[('udp', 'UDP / Diseño'), ('corte', 'Corte'), ('produccion_textil', 'Producción textil'), ('pool', 'Pool de calidad'), ('bordados', 'Bordados'), ('despacho', 'Despacho')], max_length=30)),
                ('objetivo', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('cantidad', 'Cantidad'), ('tiempo', 'Tiempo')], default='porcentaje', max_length=20)),
                ('sentido', models.CharField(choices=[('mayor', 'Mayor es mejor'), ('menor', 'Menor es mejor')], default='mayor', max_length=10)),
                ('clausula_iso', models.CharField(default='9.1', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='corte_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='observaciones_calidad_tela',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='tipo_tela_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentodespacho',
            name='fibras_hilos_sueltos_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentodespacho',
            name='observaciones_revision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='especificaciones_tecnicas',
            field=models.TextField(blank=True, help_text='Detalles de gramaje, acabados repelentes, tramado air-mesh, etc.', null=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='ficha_tecnica',
            field=models.TextField(blank=True, help_text='Ficha técnica aprobada de la prenda.'),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='rango_tallas',
            field=models.CharField(blank=True, help_text='Ej: XS a 3XL, 14.5/32 a 18/36, o Tallas 4 a 16', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='requerimiento_materiales',
            field=models.TextField(blank=True, help_text='Materiales, cantidades y tolerancias requeridas.'),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='tipo_uniforme',
            field=models.CharField(choices=[('militar', 'Uniformes Militares (Camisolas, Chaquetas, Gorras)'), ('corporativo', 'Uniformes Corporativos (Camisas, Pantalones, Blazers)'), ('deportivo', 'Uniformes Deportivos (Jerseys, Shorts, Chándales)'), ('escolar', 'Uniformes Escolares (Pantalones, Polos, Suéteres)')], default='corporativo', max_length=30),
        ),
        migrations.AlterField(
            model_name='departamentoudp',
            name='tipo_diseno',
            field=models.CharField(blank=True, help_text='Ej: Camisolas Ripstop, Polo Piqué, Jersey Dry-Fit', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='departamentoudp',
            name='tipo_tela',
            field=models.CharField(blank=True, help_text='Ej: Ripstop 65/35, Popelina, Oxford, Piqué 50/50', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MedicionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodo', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='produccion.indicadorproceso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_indicadores', to='produccion.ordenproduccion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-periodo', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('corte', 'Corte'), ('produccion_textil', 'Producción textil'), ('pool', 'Pool'), ('bordados', 'Bordados'), ('despacho', 'Despacho')], max_length=30)),
                ('descripcion', models.TextField()),
                ('cantidad_afectada', models.PositiveIntegerField(default=1)),
                ('porcentaje_rechazo', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accion_inmediata', models.TextField(blank=True)),
                ('causa_raiz', models.TextField(blank=True)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('analisis', 'En análisis'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_conformidades', to='produccion.ordenproduccion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('flujo', 'Cambio de flujo'), ('calidad', 'Alerta de calidad'), ('vencimiento', 'Vencimiento')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_produccion', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ('leida', '-creada_en'),
            },
        ),
        migrations.CreateModel(
            name='ProcesoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('udp', 'UDP / Diseño'), ('corte', 'Corte'), ('produccion_textil', 'Producción textil'), ('pool', 'Pool de calidad'), ('bordados', 'Bordados'), ('despacho', 'Despacho')], max_length=30)),
                ('objetivo', models.CharField(max_length=255)),
                ('entradas', models.TextField()),
                ('actividades', models.TextField()),
                ('salidas', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('criterios_aceptacion', models.TextField()),
                ('clausula_iso', models.CharField(default='8.5', max_length=50)),
                ('norma_venezolana', models.CharField(blank=True, max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_proceso', to='produccion.ordenproduccion')),
            ],
            options={
                'ordering': ('orden', 'departamento'),
                'constraints': [models.UniqueConstraint(fields=('orden', 'departamento', 'version'), name='unique_plan_proceso_version')],
            },
        ),
    ]
