# Generated by Django 6.0.8 on 2026-09-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_indicadorproceso_departamentocorte_corte_habilitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('objetivo', models.CharField(max_length=255)),
                ('clausula_iso', models.CharField(default='8.5', max_length=50)),
                ('norma_venezolana', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catálogo de proceso',
                'verbose_name_plural': 'Catálogo de procesos',
                'ordering': ('codigo',),
            },
        ),
    ]
