# Generated by Django 6.0.8 on 2026-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_seed_produccion_textil'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='especificacion_tecnica',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='tipo_insumo',
            field=models.CharField(choices=[('tela', 'Tela'), ('hilo', 'Hilo'), ('boton', 'Botones'), ('cremallera', 'Cremalleras'), ('goma', 'Gomas'), ('cinta', 'Cintas'), ('otro', 'Otro consumible')], default='otro', max_length=20),
        ),
    ]
