# Generated by Django 6.0.3 on 2026-09-12 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_seed_almacenes_textiles'),
        ('produccion', '0011_fichatecnica_materialfichatecnica_ordenproduccion_pedido_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('capacidad_diaria', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeoLineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('maquinas_operativas', models.PositiveIntegerField(default=0)),
                ('maquinas_con_falla', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('liberada', models.BooleanField(default=False)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chequeos', to='produccion.lineaproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaTextil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(help_text='Ej. overlock, recta, cortadora, bordadora', max_length=100)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('operativa', 'Operativa'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='operativa', max_length=20)),
                ('horas_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='produccion.lineaproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimientoTextil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_mantenimiento', to='produccion.maquinatextil')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantenimientoTextil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia_dias', models.PositiveIntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_mantenimiento', to='produccion.lineaproduccion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPiezaMecanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('atendida', 'Atendida'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_piezas', to='produccion.maquinatextil')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_mecanica', to='logistica.repuestomaquina')),
                ('solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
