# Generated by Django 6.0.3 on 2026-09-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_seed_almacenes_textiles'),
        ('produccion', '0012_lineaproduccion_chequeolineaproduccion_maquinatextil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpiezamecanica',
            name='especificacion_pieza',
            field=models.TextField(blank=True, verbose_name='Especificación de la pieza'),
        ),
        migrations.AddField(
            model_name='solicitudpiezamecanica',
            name='pieza_nueva',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de pieza nueva'),
        ),
        migrations.AlterField(
            model_name='solicitudpiezamecanica',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_mecanica', to='logistica.repuestomaquina'),
        ),
    ]
