# Generated by Django 6.0.8 on 2026-09-14 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0013_solicitudpiezamecanica_especificacion_pieza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentocorte',
            name='aprovechamiento_tela',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='calidad_post_corte_aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='carro_carga',
            field=models.CharField(default='Carro de carga de corte', max_length=100),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='conteo_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='control_calidad_en_proceso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='enviado_carro_carga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='equipo_corte',
            field=models.TextField(blank=True, help_text='Cortadores y ayudantes que participan.'),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_mesa', 'En mesa de corte'), ('calidad_proceso', 'Calidad en proceso'), ('habilitado', 'Habilitado'), ('calidad_post', 'Calidad post corte'), ('enviado', 'Enviado a confección'), ('retenido', 'Retenido por corrección')], default='programado', max_length=20),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='fusion_verificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='instrucciones_jefatura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='instrumento_tecnico',
            field=models.CharField(blank=True, help_text='Ficha técnica, medidas, color, talla y estilo.', max_length=255),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='jefe_corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefaturas_corte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='linea_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_recibidos', to='produccion.lineaproduccion'),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='materiales_verificados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='mesa_calidad',
            field=models.CharField(default='Mesa de calidad', max_length=100),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='mesa_corte',
            field=models.CharField(default='Mesa principal', max_length=100),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='mesa_habilitado',
            field=models.CharField(default='Mesa de habilitado', max_length=100),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='observaciones_calidad_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='observaciones_calidad_proceso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='observaciones_materiales',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='orden_corte',
            field=models.CharField(blank=True, help_text='Número o referencia de la orden de corte.', max_length=50),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='paquete_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='piezas_fusionadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='piezas_habilitadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='ruta_corte',
            field=models.CharField(default='Mesa de corte', max_length=100),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='supervisor_mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisiones_mesa_corte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamentocorte',
            name='tizado',
            field=models.CharField(choices=[('digital', 'Tizado digital'), ('manual', 'Tizado manual')], default='digital', max_length=10),
        ),
    ]
