# Generated by Django 6.0.8 on 2026-09-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0014_departamentocorte_aprovechamiento_tela_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='actividades_realizadas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='bloqueo_seguridad_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='garantia_trabajo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='minuta_registrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='muestra_costura_aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordenmantenimientotextil',
            name='prueba_costura_realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='actividades_programadas',
            field=models.TextField(blank=True, help_text='Actividades, diagnóstico y mantenimientos previstos.'),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='alcance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_mantenimiento_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('cerrado', 'Cerrado')], default='borrador', max_length=25),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='objetivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='planmantenimientotextil',
            name='periodicidad',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=15),
        ),
        migrations.CreateModel(
            name='ActividadPlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=20)),
                ('frecuencia', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=15)),
                ('checklist', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='produccion.planmantenimientotextil')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoElementoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_elemento', models.CharField(max_length=80)),
                ('elemento', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('desgaste', 'Desgaste'), ('defectuoso', 'Defectuoso'), ('faltante', 'Faltante')], max_length=15)),
                ('resultado', models.TextField()),
                ('requiere_repuesto', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('diagnosticado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='produccion.maquinatextil')),
            ],
        ),
        migrations.CreateModel(
            name='MinutaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('actividades_realizadas', models.TextField()),
                ('novedades', models.TextField(blank=True)),
                ('restricciones_operacion', models.TextField(blank=True)),
                ('herramientas_verificadas', models.BooleanField(default=False)),
                ('seguridad_verificada', models.BooleanField(default=False)),
                ('entregada_jefatura', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('maquinas_intervenidas', models.ManyToManyField(blank=True, related_name='minutas', to='produccion.maquinatextil')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-creada_en'),
            },
        ),
        migrations.CreateModel(
            name='TrasladoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_origen', models.CharField(max_length=150)),
                ('ubicacion_destino', models.CharField(max_length=150)),
                ('orden_ingenieria', models.CharField(help_text='Referencia de la orden firmada por Ingeniería.', max_length=100)),
                ('ficha_traslado', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('supervisado', 'Supervisado'), ('aprobado', 'Aprobado por jefatura'), ('en_traslado', 'En traslado'), ('instalado', 'Instalado y calibrado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ajuste_calibracion_realizado', models.BooleanField(default=False)),
                ('espacios_linea_verificados', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_aprobados', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='produccion.maquinatextil')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_supervisados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
