# Generated by Django 6.0.8 on 2026-09-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0015_ordenmantenimientotextil_actividades_realizadas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], default='diurno', max_length=15)),
                ('periodo', models.CharField(choices=[('06:00-08:00', '06:00 - 08:00'), ('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('12:00-14:00', '12:00 - 14:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00'), ('18:00-20:00', '18:00 - 20:00'), ('20:00-22:00', '20:00 - 22:00')], max_length=15)),
                ('meta_piezas', models.PositiveIntegerField(default=0)),
                ('piezas_buenas', models.PositiveIntegerField(default=0)),
                ('piezas_rechazadas', models.PositiveIntegerField(default=0)),
                ('minutos_planificados', models.PositiveIntegerField(default=120)),
                ('minutos_parada', models.PositiveIntegerField(default=0)),
                ('causa_parada', models.CharField(blank=True, max_length=255)),
                ('cuello_botella', models.CharField(blank=True, max_length=255)),
                ('materiales_disponibles', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_turno', to='produccion.lineaproduccion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_turno', to='produccion.ordenproduccion')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_produccion_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-creado_en'),
                'constraints': [models.UniqueConstraint(fields=('orden', 'linea', 'fecha', 'turno', 'periodo'), name='unique_registro_turno_linea')],
            },
        ),
    ]
