# Generated by Django 6.0.8 on 2026-09-14 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0016_registroproduccionturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noconformidad',
            name='autoridad_concesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concesiones_calidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='concesion',
            field=models.TextField(blank=True, help_text='Autorización documentada cuando se libera una salida no conforme.'),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='criterio_eficacia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='detectada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_conformidades_detectadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='eficaz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='fecha_verificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='requisito',
            field=models.CharField(blank=True, help_text='Requisito del producto, proceso, cliente o norma incumplido.', max_length=255),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='resuelta_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='resultado_eficacia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='riesgo',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], default='medio', max_length=10),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='tipo',
            field=models.CharField(choices=[('nc', 'No conformidad'), ('om', 'Oportunidad de mejora'), ('snc', 'Salida no conforme')], default='nc', max_length=5),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='tratamiento',
            field=models.CharField(choices=[('correccion', 'Corrección'), ('reproceso', 'Reproceso'), ('contencion', 'Separación / contención'), ('rechazo', 'Rechazo / desecho'), ('liberacion', 'Liberación bajo concesión')], default='correccion', max_length=20),
        ),
        migrations.AddField(
            model_name='noconformidad',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('analisis', 'En análisis'), ('implementada', 'Acción implementada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20),
        ),
        migrations.AlterField(
            model_name='noconformidad',
            name='origen',
            field=models.CharField(choices=[('compras', 'Compras / recepción'), ('udp', 'UDP / Diseño'), ('corte', 'Corte'), ('produccion_textil', 'Producción textil'), ('pool', 'Pool / Calidad'), ('bordados', 'Bordados'), ('despacho', 'Despacho'), ('post_entrega', 'Post-entrega'), ('otro', 'Otro')], max_length=30),
        ),
    ]
