# Generated by Django 6.0.8 on 2026-09-14 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0017_noconformidad_autoridad_concesion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentoudp',
            name='aprobacion_muestra_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_udp_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='fecha_aprobacion_muestra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='hoja_medidas_molde',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='muestra_aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='observaciones_muestra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='referencia_archivo_audaces',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='referencia_muestra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='tallas_escaladas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='tizado_disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamentoudp',
            name='version_molde_digital',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='MuestraPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('requisitos_cliente', models.TextField(blank=True)),
                ('referencia_fisica', models.CharField(blank=True, max_length=255)),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('medidas_verificadas', models.TextField(blank=True)),
                ('resultado_calidad', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('en_desarrollo', 'En desarrollo'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=20)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='produccion.ordenproduccion')),
                ('solicitada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
        migrations.CreateModel(
            name='DigitalizacionMolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molde_base', models.CharField(max_length=255)),
                ('sistema', models.CharField(default='Audaces', max_length=80)),
                ('version', models.CharField(default='1.0', max_length=30)),
                ('piezas_digitalizadas', models.PositiveIntegerField(default=0)),
                ('tallas_escaladas', models.CharField(max_length=200)),
                ('hoja_medidas', models.TextField(blank=True)),
                ('referencia_archivo', models.CharField(blank=True, max_length=255)),
                ('tizado_referencia', models.CharField(blank=True, max_length=255)),
                ('aprovechamiento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_digitalizacion', 'En digitalización'), ('escalado', 'Escalado'), ('validado', 'Validado para tizado'), ('rechazado', 'Requiere corrección')], default='pendiente', max_length=25)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitalizaciones_analista', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitalizaciones', to='produccion.ordenproduccion')),
                ('patronista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitalizaciones_patronista', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitalizaciones_validadas', to=settings.AUTH_USER_MODEL)),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digitalizaciones', to='produccion.muestraprenda')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='semanal', max_length=15)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('meta_piezas', models.PositiveIntegerField(default=0)),
                ('capacidad_disponible', models.PositiveIntegerField(default=0)),
                ('tiempo_estandar_minutos', models.PositiveIntegerField(default=0)),
                ('disponibilidad_maquinaria', models.TextField(blank=True)),
                ('calidad_materia_prima', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('escenario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validada', 'Validada'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='produccion.lineaproduccion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='produccion.ordenproduccion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_produccion', to=settings.AUTH_USER_MODEL)),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_validadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('hoja_consumo_disponible', models.BooleanField(default=False)),
                ('solicitud_materiales_disponible', models.BooleanField(default=False)),
                ('tiempo_estandar_minutos', models.PositiveIntegerField(default=0)),
                ('secuencia_fabricacion', models.TextField(blank=True)),
                ('cuotas_produccion', models.TextField(blank=True)),
                ('areas_distribuidas', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validacion', 'En validación'), ('aprobada', 'Aprobada'), ('distribuida', 'Distribuida'), ('cerrada', 'Cerrada')], default='borrador', max_length=15)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('elaborada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo_elaboradas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='produccion.ordenproduccion')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='produccion.programacionproduccion')),
            ],
        ),
    ]
