# Generated by Django 6.0.8 on 2026-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0018_departamentoudp_aprobacion_muestra_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestraprenda',
            name='aprobacion_origen',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('gerencia', 'Gerencia de Producción')], max_length=15),
        ),
        migrations.AddField(
            model_name='muestraprenda',
            name='calidad_final_aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muestraprenda',
            name='confeccion_completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muestraprenda',
            name='corte_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
