# Generated by Django 6.0.8 on 2026-09-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_empleado_bono_alimentacion_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('organismo', models.CharField(max_length=150)),
                ('jurisdiccion', models.CharField(default='Venezuela', max_length=80)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('vigente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('asunto', models.CharField(max_length=180)),
                ('area_solicitante', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(default='media', max_length=15)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_analisis', 'En análisis'), ('en_tramite', 'En trámite'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='recibido', max_length=15)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('confidencial', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_juridicos', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('objeto', models.CharField(max_length=200)),
                ('contraparte', models.CharField(max_length=180)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('vigente', 'Vigente'), ('vencido', 'Vencido'), ('rescindido', 'Rescindido')], default='borrador', max_length=12)),
                ('documento', models.FileField(blank=True, upload_to='juridica/contratos/%Y/%m/')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_juridicos', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DictamenJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('asunto', models.CharField(max_length=180)),
                ('fundamentos', models.TextField()),
                ('recomendacion', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('documento', models.FileField(blank=True, upload_to='juridica/dictamenes/%Y/%m/')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictamenes', to='consultoria_juridica.casojuridico')),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictamenes_juridicos', to='rrhh.empleado')),
            ],
        ),
    ]
