# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='comercial/categorias/')),
            ],
            options={
                'verbose_name_plural': 'Categorías Comerciales',
            },
        ),
        migrations.CreateModel(
            name='ItemPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('factor_ajuste', models.DecimalField(decimal_places=2, default=1.0, help_text='Factor multiplicador global (opcional)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('descripcion_larga', models.TextField(help_text='Descripción detallada para catálogos o web')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='comercial/fichas/')),
                ('en_oferta', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='comercializacion.categoriacomercial')),
            ],
        ),
    ]
