# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercializacion', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioncomercial',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_comercial', to='produccion.productoterminado'),
        ),
        migrations.AddField(
            model_name='itemprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.productoterminado'),
        ),
        migrations.AddField(
            model_name='itemprecio',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comercializacion.listaprecio'),
        ),
        migrations.AlterUniqueTogether(
            name='itemprecio',
            unique_together={('lista', 'producto')},
        ),
    ]
