# Generated by Django 6.0.8 on 2026-09-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacioncomercial',
            name='colores_disponibles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='informacioncomercial',
            name='composicion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informacioncomercial',
            name='tallas_disponibles',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informacioncomercial',
            name='unidad_venta',
            field=models.CharField(default='unidad', max_length=30),
        ),
    ]
