# Generated by Django 6.0.3 on 2026-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializacion', '0003_informacioncomercial_colores_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaprecio',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
