# Generated by Django 6.0.8 on 2026-09-14 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializacion', '0004_alter_listaprecio_moneda'),
        ('produccion', '0016_registroproduccionturno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('genero', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('tipo_tela', models.CharField(blank=True, max_length=200)),
                ('tallas', models.CharField(blank=True, max_length=200)),
                ('cantidades_talla', models.JSONField(blank=True, default=dict)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('materiales', models.JSONField(blank=True, default=list)),
                ('hoja_consumo', models.TextField(blank=True)),
                ('orden_trabajo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_solicitud', models.CharField(default='Producción', max_length=80)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validacion', 'En validación'), ('enviada', 'Enviada a Producción'), ('ejecutando', 'En ejecución'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_comerciales_produccion', to=settings.AUTH_USER_MODEL)),
                ('orden_produccion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_comercial_origen', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.productoterminado')),
            ],
            options={
                'verbose_name': 'Orden comercial de producción',
                'verbose_name_plural': 'Órdenes comerciales de producción',
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
    ]
