# Generated by Django 6.0.8 on 2026-09-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializacion', '0005_ordenproduccioncomercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSatisfaccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=150)),
                ('cumplimiento_requerimientos', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Mejorable'), ('D', 'Deficiente')], max_length=1)),
                ('tiempo_respuesta', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Mejorable'), ('D', 'Deficiente')], max_length=1)),
                ('calidad_servicio', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Mejorable'), ('D', 'Deficiente')], max_length=1)),
                ('atencion_personal', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Mejorable'), ('D', 'Deficiente')], max_length=1)),
                ('producto_servicio', models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('R', 'Regular'), ('M', 'Mejorable'), ('D', 'Deficiente')], max_length=1)),
                ('comentarios', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('respondida_por', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_satisfaccion', to='comercializacion.ordenproduccioncomercial')),
                ('registrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
