# Generated by Django 6.0.8 on 2026-09-14 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercializacion', '0006_encuestasatisfaccioncliente'),
        ('produccion', '0019_muestraprenda_aprobacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('fecha_recepcion', models.DateField()),
                ('canal', models.CharField(choices=[('digital', 'Digital'), ('escrito', 'Escrito')], default='digital', max_length=10)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('causa', models.TextField(blank=True)),
                ('acciones', models.TextField(blank=True)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_investigacion', 'En investigación'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='recibido', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='comercializacion.ordenproduccioncomercial')),
            ],
            options={
                'ordering': ('-fecha_recepcion', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.CharField(choices=[('fabricado', 'Producto fabricado por planta'), ('comercializado', 'Producto no fabricado por planta')], default='fabricado', max_length=20)),
                ('requerimiento', models.TextField(help_text='Especificaciones técnicas y cantidades solicitadas.')),
                ('fecha_recepcion', models.DateField()),
                ('fecha_limite_cotizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_analisis', 'En análisis'), ('cotizada', 'Cotizada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='recibida', max_length=20)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.productoterminado')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ('-fecha_recepcion', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='CotizacionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('moneda', models.CharField(default='VES', max_length=3)),
                ('condiciones_pago', models.CharField(blank=True, max_length=250)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('vencida', 'Vencida'), ('rechazada', 'Rechazada')], default='borrador', max_length=15)),
                ('aprobada_por_cliente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion', to='comercializacion.solicitudcotizacion')),
            ],
            options={
                'ordering': ('-fecha', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='SolicitudDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('beneficiario', models.CharField(max_length=200)),
                ('institucion_solicitante', models.CharField(max_length=250)),
                ('fecha_solicitud', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('justificacion', models.TextField()),
                ('aprobacion_presidencia', models.BooleanField(default=False)),
                ('contrato_donacion', models.FileField(blank=True, null=True, upload_to='comercial/donaciones/')),
                ('carta_aceptacion', models.FileField(blank=True, null=True, upload_to='comercial/donaciones/')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada')], default='recibida', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.productoterminado')),
            ],
            options={
                'verbose_name': 'Solicitud de donación',
                'verbose_name_plural': 'Solicitudes de donación',
                'ordering': ('-fecha_solicitud', '-creado_en'),
            },
        ),
    ]
