# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_impuesto', models.CharField(choices=[('exento', 'Exento'), ('general', 'General (16%)'), ('reducida', 'Reducida (8%)'), ('suntuaria', 'Suntuaria (31%)')], default='general', max_length=20)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50)),
                ('numero_control', models.CharField(help_text='Número de control fiscal', max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('exento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible_reducida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_imponible_suntuaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_iva_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_iva_reducida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_iva_suntuaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('igtf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='registrada', max_length=20)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('recibida', 'Recibida')], default='borrador', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
        ),
    ]
