# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra', to='facturacion.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='compras.ordencompra'),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('proveedor', 'numero_factura')},
        ),
    ]
