# Generated by Django 6.0.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
        ('produccion', '0008_seed_produccion_textil'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('atendido', 'Atendido'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='productocompra',
            name='especificacion_textil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productocompra',
            name='tipo',
            field=models.CharField(choices=[('tela', 'Tela'), ('hilo', 'Hilo'), ('consumible', 'Consumible textil'), ('repuesto', 'Repuesto de máquina'), ('servicio', 'Servicio')], default='consumible', max_length=20),
        ),
        migrations.AddField(
            model_name='productocompra',
            name='unidad_medida',
            field=models.CharField(default='unidad', max_length=20),
        ),
        migrations.CreateModel(
            name='DetalleRequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('especificacion', models.TextField(blank=True)),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='produccion.materiaprima')),
            ],
        ),
    ]
