# Generated by Django 6.0.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_requerimientomaterial_and_more'),
        ('logistica', '0003_repuestomaquina_and_more'),
        ('produccion', '0008_seed_produccion_textil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequerimientomaterial',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.repuestomaquina'),
        ),
        migrations.AddField(
            model_name='requerimientomaterial',
            name='orden_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_compra', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='requerimientomaterial',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallerequerimientomaterial',
            name='requerimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.requerimientomaterial'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='requerimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='compras.requerimientomaterial'),
        ),
    ]
