# Generated by Django 6.0.8 on 2026-09-12 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detallerequerimientomaterial_repuesto_and_more'),
        ('logistica', '0004_seed_almacenes_textiles'),
        ('produccion', '0009_materiaprima_especificacion_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefacturacompra',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_facturas_compra', to='produccion.materiaprima'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_facturas_compra', to='logistica.repuestomaquina'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='almacen_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_compra_recibidas', to='logistica.almacen'),
        ),
    ]
