# Generated by Django 6.0.3 on 2026-09-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_detalleordencompra_recepcioncompra_and_more'),
        ('logistica', '0004_seed_almacenes_textiles'),
        ('produccion', '0013_solicitudpiezamecanica_especificacion_pieza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimientomaterial',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'tipo': 'repuestos'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_compra', to='logistica.almacen'),
        ),
        migrations.AddField(
            model_name='requerimientomaterial',
            name='solicitud_pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_compra', to='produccion.solicitudpiezamecanica'),
        ),
        migrations.AlterField(
            model_name='requerimientomaterial',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_compra', to='produccion.ordenproduccion'),
        ),
    ]
