# Generated by Django 6.0.3 on 2026-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_requerimientomaterial_almacen_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='productocompra',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
