# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use cedula venezolana o extranjera. Ej: V-12345678.', regex='^[VE]-?\\d{6,9}$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('numero_licencia', models.CharField(blank=True, max_length=30)),
                ('categoria_licencia', models.CharField(blank=True, choices=[('2', '2do grado'), ('3', '3er grado'), ('4', '4to grado'), ('5', '5to grado / carga pesada')], max_length=2)),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('certificado_medico_vencimiento', models.DateField(blank=True, null=True)),
                ('curso_carga_pesada', models.BooleanField(default=False)),
                ('curso_materiales_peligrosos', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('vacaciones', 'De Vacaciones')], default='activo', max_length=12)),
                ('foto', models.FileField(blank=True, null=True, upload_to='conductores/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PuntoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cliente_ref', models.CharField(blank=True, help_text='Nombre del cliente en este punto', max_length=200)),
                ('tiempo_estimado', models.PositiveIntegerField(default=0, help_text='Minutos desde el inicio de la ruta')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto de Entrega',
                'verbose_name_plural': 'Puntos de Entrega',
                'ordering': ['ruta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=200)),
                ('latitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud Origen')),
                ('longitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud Origen')),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('tiempo_estimado', models.PositiveIntegerField(default=0, help_text='Tiempo estimado en minutos')),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['zona', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En Ruta'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('con_novedad', 'Con Novedad')], default='programado', max_length=15)),
                ('numero_guia_despacho', models.CharField(blank=True, max_length=60)),
                ('numero_control_guia', models.CharField(blank=True, max_length=60, verbose_name='Nro. control guia')),
                ('rif_transportista', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use RIF venezolano. Ej: J-12345678-9.', regex='^[JGVEP]-?\\d{7,9}-?\\d?$')])),
                ('descripcion_carga', models.CharField(blank=True, max_length=255)),
                ('peso_carga_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('declara_material_peligroso', models.BooleanField(default=False)),
                ('odometro_salida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('odometro_llegada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('km_recorridos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('combustible_usado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Galones/litros usados', max_digits=8)),
                ('costo_combustible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('novedad', models.TextField(blank=True, help_text='Descripción de novedad si aplica')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transportes.conductor')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_creados', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transportes.ruta')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='EntregaDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('no_entregado', 'No Entregado'), ('parcial', 'Entrega Parcial')], default='pendiente', max_length=15)),
                ('firma_receptor', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='transportes.despacho')),
                ('punto_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='transportes.puntoentrega')),
            ],
            options={
                'verbose_name': 'Entrega de Despacho',
                'verbose_name_plural': 'Entregas de Despacho',
                'ordering': ['punto_entrega__orden'],
            },
        ),
        migrations.AddField(
            model_name='puntoentrega',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='transportes.ruta'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('gas', 'Gas'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='gasolina', max_length=10)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capacidad en toneladas', max_digits=8)),
                ('capacidad_volumen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capacidad en m³', max_digits=8)),
                ('odometro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Odómetro (km)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='disponible', max_length=15)),
                ('soat_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento SOAT')),
                ('revision_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento Revisión Técnica')),
                ('seguro_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro')),
                ('certificado_registro', models.CharField(blank=True, max_length=60, verbose_name='Certificado de registro vehicular')),
                ('poliza_rcv', models.CharField(blank=True, max_length=60, verbose_name='Poliza RCV')),
                ('permiso_carga', models.CharField(blank=True, max_length=80, verbose_name='Permiso / habilitacion de carga')),
                ('permiso_carga_vencimiento', models.DateField(blank=True, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='vehiculos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='transportes.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('revision', 'Revisión')], max_length=12)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=12)),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taller', models.CharField(blank=True, max_length=200)),
                ('km_en_servicio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('km_proximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Próximo mantenimiento (km)')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='transportes.vehiculo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='transportes.vehiculo'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductores', to='transportes.vehiculo'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='transportes.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='puntoentrega',
            unique_together={('ruta', 'orden')},
        ),
    ]
