# Generated by Django 6.0.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
        ('ventas', '0003_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_transportes', to='ventas.pedido'),
        ),
    ]
