# Generated by Django 6.0.8 on 2026-09-12 15:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0002_despacho_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='autorizacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='despacho',
            name='material_orden',
            field=models.CharField(blank=True, max_length=255, verbose_name='Material según orden'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='tipo_ruta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='despacho',
            name='viatico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ViaticoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado'), ('rendido', 'Rendido')], default='solicitado', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='transportes/viaticos/')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaticos', to='transportes.despacho')),
            ],
        ),
    ]
