# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, null=True)),
                ('fecha_viaje', models.DateField()),
                ('destino', models.CharField(max_length=200)),
                ('motivo', models.TextField()),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('moneda', models.CharField(choices=[('VES', 'Bolivares'), ('USD', 'Dolares')], default='VES', max_length=3)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('rendido', 'Rendido')], default='pendiente', max_length=20)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaticos', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='GastoViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte'), ('alojamiento', 'Alojamiento'), ('alimentacion', 'Alimentación'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('VES', 'Bolivares'), ('USD', 'Dolares')], default='VES', max_length=3)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12)),
                ('proveedor_rif', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use RIF venezolano. Ej: J-12345678-9.', regex='^[JGVEP]-?\\d{7,9}-?\\d?$')])),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('nro_factura', models.CharField(blank=True, max_length=50, verbose_name='Nro. factura')),
                ('nro_control', models.CharField(blank=True, max_length=50, verbose_name='Nro. control')),
                ('es_reembolsable', models.BooleanField(default=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_viaticos/')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viaticos.solicitudviatico')),
            ],
        ),
    ]
