# Generated by Django 6.0.4 on 2026-05-07 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
        ('viaticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudviatico',
            name='beneficiario_cargo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='solicitudviatico',
            name='beneficiario_departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='solicitudviatico',
            name='beneficiario_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Beneficiario'),
        ),
        migrations.AlterField(
            model_name='solicitudviatico',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text='Seleccione si es un empleado registrado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaticos', to='rrhh.empleado'),
        ),
    ]
