# Generated by Django 6.0.3 on 2026-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0002_solicitudviatico_beneficiario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoviatico',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='VES', max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudviatico',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='VES', max_length=3),
        ),
    ]
