# Generated by Django 6.0.3 on 2026-09-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaticos', '0003_alter_gastoviatico_moneda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoviatico',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolivares'), ('USD', 'Dolares'), ('EUR', 'Euros')], default='VES', max_length=3),
        ),
        migrations.AlterField(
            model_name='solicitudviatico',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolivares'), ('USD', 'Dolares'), ('EUR', 'Euros')], default='VES', max_length=3),
        ),
    ]
