# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo_codigo', models.CharField(help_text='Ej: MAQ para Maquinaria', max_length=5)),
                ('vida_util_defecto', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Activos',
            },
        ),
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('etiqueta', models.CharField(blank=True, help_text='Para control físico', max_length=100, null=True, verbose_name='Etiqueta / Código de Barras')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serial')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Activo')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de Adquisición')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Adquisición')),
                ('valor_residual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vida_util_anios', models.PositiveIntegerField(default=5)),
                ('metodo_depreciacion', models.CharField(choices=[('lineal', 'Líneal'), ('decremento', 'Decremento Doble')], default='lineal', max_length=20)),
                ('estado', models.CharField(default='Operativo', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación Física')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.empleado', verbose_name='Responsable Directo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos_fijos.categoriaactivo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(help_text='Nombre del empleado o responsable', max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_asignacion', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado_entrega', models.CharField(default='Buen estado', max_length=100)),
                ('estado_devolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='activos_fijos.activofijo')),
            ],
        ),
        migrations.CreateModel(
            name='MantenimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('proveedor', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos_fijos.activofijo')),
            ],
        ),
    ]
