# Generated by Django 6.0.4 on 2026-05-07 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos_fijos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activofijo',
            name='anio_fabricacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Fabricación'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción detallada (Sudebip)'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='activos_fijos.categoriaactivo', verbose_name='Clasificación / Tipo de Activo'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario (Bien Nacional)'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='estado',
            field=models.CharField(default='Operativo', max_length=50, verbose_name='Estado de Conservación'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='fecha_adquisicion',
            field=models.DateField(verbose_name='Fecha de Adquisición / Incorporación'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo / Valor de Adquisición'),
        ),
        migrations.AlterField(
            model_name='activofijo',
            name='vida_util_anios',
            field=models.PositiveIntegerField(default=5, verbose_name='Años de Vida Útil'),
        ),
    ]
