# Generated by Django 6.0.8 on 2026-09-15 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(max_length=120)),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones')], default='activo', max_length=12)),
                ('supervisor', models.CharField(blank=True, max_length=180)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Personal de servicios generales',
                'verbose_name_plural': 'Personal de servicios generales',
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(default='Área', max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TareaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('hora_programada', models.TimeField(blank=True, null=True)),
                ('hora_ejecucion', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada'), ('no_realizada', 'No realizada')], default='pendiente', max_length=15)),
                ('evidencia', models.FileField(blank=True, upload_to='servicios/tareas/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='servicios_generales.personalservicios')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='servicios_generales.ubicacion')),
            ],
            options={
                'ordering': ('-fecha', 'hora_programada'),
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('interno', 'Servicio interno'), ('contratista', 'Contratista'), ('emergencia', 'Emergencia')], default='interno', max_length=15)),
                ('servicio_requerido', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(default='media', max_length=20)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('asignada', 'Asignada'), ('en_ejecucion', 'En ejecución'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=15)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_asignados', to='servicios_generales.personalservicios')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_servicio', to='servicios_generales.personalservicios')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_servicio', to='servicios_generales.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.CharField(max_length=180)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad', models.CharField(max_length=30)),
                ('justificacion', models.TextField()),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='solicitada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_aprobados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_material', to='servicios_generales.personalservicios')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_material', to='servicios_generales.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=12)),
                ('equipo_o_area', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(default='media', max_length=20)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('programado', 'Programado'), ('en_ejecucion', 'En ejecución'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='servicios_generales.personalservicios')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='servicios_generales.ubicacion')),
            ],
            options={
                'ordering': ('-fecha_programada', '-codigo'),
            },
        ),
        migrations.AddField(
            model_name='personalservicios',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='servicios_generales.ubicacion'),
        ),
        migrations.CreateModel(
            name='EquipoServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('marca_modelo', models.CharField(blank=True, max_length=150)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado'), ('baja', 'Dado de baja')], default='operativo', max_length=15)),
                ('valor_referencial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('custodio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_custodiados', to='servicios_generales.personalservicios')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='servicios_generales.ubicacion')),
            ],
            options={
                'ordering': ('categoria', 'nombre'),
            },
        ),
    ]
