# Generated by Django 6.0.8 on 2026-09-14 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0008_detalleordencompra_moneda_facturacompra_moneda_and_more'),
        ('produccion', '0018_departamentoudp_aprobacion_muestra_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionOrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=120)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('recibido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones_pcpi', to='produccion.ordentrabajoproduccion')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_entrega_comprometida', models.DateField(blank=True, null=True)),
                ('tiempo_estandar_minutos', models.PositiveIntegerField(default=0)),
                ('dias_habiles_requeridos', models.PositiveIntegerField(default=0)),
                ('secuencia_fabricacion', models.TextField()),
                ('disponibilidad_lineas', models.TextField(blank=True)),
                ('disponibilidad_maquinaria', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('escenarios', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('validada', 'Validada por Gerencia'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones_pcpi', to='produccion.ordenproduccion')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_pcpi', to=settings.AUTH_USER_MODEL)),
                ('validada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones_pcpi_validadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fin', models.DateField()),
                ('notas_entrega_materiales', models.TextField(blank=True)),
                ('informe_calidad_materia_prima', models.TextField(blank=True)),
                ('tiempos_estandar', models.TextField(blank=True)),
                ('disponibilidad_maquinaria', models.TextField(blank=True)),
                ('cuotas_produccion', models.PositiveIntegerField(default=0)),
                ('eficiencia_referencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('restricciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('validada', 'Validada por Gerencia'), ('distribuida', 'Distribuida'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('distribuido_a', models.CharField(blank=True, help_text='UDP, Producción, Ingeniería y Calidad', max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('elaborado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_semanales_pcpi', to=settings.AUTH_USER_MODEL)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_semanales', to='pcpi.planificacionentrega')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones_semanales_validadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumenRequerimientosMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('hoja_consumo_referencia', models.CharField(max_length=255)),
                ('nota_entrega_referencia', models.CharField(blank=True, max_length=255)),
                ('materiales_transcritos', models.TextField()),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unidad_medida', models.CharField(default='unidad', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('emitido', 'Emitido'), ('validado', 'Validado y sellado'), ('atendido', 'Atendido por Almacén'), ('archivado', 'Archivado')], default='borrador', max_length=20)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('elaborado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_materiales_pcpi', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_materiales_pcpi', to='produccion.ordenproduccion')),
                ('requerimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_pcpi', to='compras.requerimientomaterial')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumenes_materiales_pcpi_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
