# Generated by Django 6.0.8 on 2026-09-15 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rrhh', '0005_empleado_bono_alimentacion_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=180)),
                ('organismo', models.CharField(max_length=150)),
                ('jurisdiccion', models.CharField(default='Venezuela', max_length=80)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallazgoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('proceso', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('no_conformidad_mayor', 'No conformidad mayor'), ('no_conformidad_menor', 'No conformidad menor'), ('observacion', 'Observación'), ('oportunidad', 'Oportunidad de mejora')], max_length=25)),
                ('descripcion', models.TextField()),
                ('criterio', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('plan_accion', 'En plan de acción'), ('verificado', 'Verificado'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos_auditoria', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField()),
                ('fecha_compromiso', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, upload_to='auditoria/evidencias/%Y/%m/')),
                ('verificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_correctivas', to='rrhh.empleado')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='auditoria_interna.hallazgoauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('ejercicio', models.PositiveIntegerField()),
                ('alcance', models.TextField()),
                ('objetivo', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En ejecución'), ('cerrado', 'Cerrado')], default='borrador', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_auditoria', to='rrhh.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='hallazgoauditoria',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hallazgos', to='auditoria_interna.planauditoria'),
        ),
        migrations.AlterUniqueTogether(
            name='hallazgoauditoria',
            unique_together={('plan', 'codigo')},
        ),
    ]
