# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(blank=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use cedula venezolana o extranjera. Ej: V-12345678.', regex='^[VE]-?\\d{6,9}$')])),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('meta_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_venta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('monto_comision', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('retencion_islr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('referencia_pago', models.CharField(blank=True, max_length=80)),
                ('pagado', models.BooleanField(default=False)),
                ('pedido_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to='ventas.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedores.vendedor')),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]
