# Generated by Django 6.0.8 on 2026-09-15 14:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('uniforme', 'Uniforme'), ('epp', 'EPP'), ('comunicacion', 'Comunicación'), ('defensa', 'Defensa autorizada'), ('otro', 'Otro')], max_length=20)),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('requiere_vencimiento', models.BooleanField(default=False)),
                ('especificacion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo de seguridad',
                'verbose_name_plural': 'Equipos de seguridad',
                'ordering': ('tipo', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=180)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=12)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('capacitacion_vigente_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Guardia de seguridad',
                'verbose_name_plural': 'Guardias de seguridad',
                'ordering': ('nombre_completo',),
            },
        ),
        migrations.CreateModel(
            name='InspeccionSST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('area', models.CharField(max_length=180)),
                ('inspector', models.CharField(max_length=180)),
                ('referencia_normativa', models.CharField(blank=True, max_length=250)),
                ('hallazgos', models.TextField(blank=True)),
                ('acciones_correctivas', models.TextField(blank=True)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('ejecutada', 'Ejecutada'), ('con_hallazgos', 'Con hallazgos'), ('cerrada', 'Cerrada')], default='planificada', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NormaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.CharField(default='Venezuela', max_length=80)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('ambito', models.CharField(help_text='Seguridad industrial, SST, control de acceso, etc.', max_length=120)),
                ('organismo', models.CharField(blank=True, max_length=180)),
                ('version_vigente', models.CharField(blank=True, max_length=60)),
                ('enlace_oficial', models.URLField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('jurisdiccion', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='PuestoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Puesto de seguridad',
                'verbose_name_plural': 'Puestos de seguridad',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='DotacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('entregado', 'Entregado'), ('devuelto', 'Devuelto'), ('perdido', 'Reportado perdido'), ('mantenimiento', 'En mantenimiento')], default='entregado', max_length=16)),
                ('observaciones', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotaciones', to='seguridad.equiposeguridad')),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotaciones', to='seguridad.guardia')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('intrusion', 'Intrusión'), ('accidente', 'Accidente'), ('incendio', 'Incendio'), ('derrame', 'Derrame'), ('robo', 'Pérdida o robo'), ('otro', 'Otro')], max_length=15)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('ubicacion', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('acciones_inmediatas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('investigacion', 'En investigación'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('responsable', models.CharField(blank=True, max_length=180)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenSalidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitante', models.CharField(max_length=180)),
                ('destino', models.CharField(max_length=200)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('conductor', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('autorizada', 'Autorizada'), ('verificada', 'Verificada'), ('anulada', 'Anulada')], default='solicitada', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='MaterialSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unidad', models.CharField(max_length=20)),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('verificado', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='seguridad.ordensalidamaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PaseIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('visitante', 'Visitante'), ('contratista', 'Contratista'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('vehiculo', 'Vehículo')], max_length=15)),
                ('nombre_visitante', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('empresa', models.CharField(blank=True, max_length=180)),
                ('motivo', models.CharField(max_length=250)),
                ('persona_responsable', models.CharField(blank=True, max_length=180)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('autorizado', 'Autorizado'), ('usado', 'Usado'), ('anulado', 'Anulado'), ('vencido', 'Vencido')], default='solicitado', max_length=12)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pases_autorizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('rechazo', 'Acceso rechazado')], max_length=10)),
                ('persona', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(blank=True, max_length=20)),
                ('notificado_a', models.CharField(blank=True, max_length=180)),
                ('observaciones', models.TextField(blank=True)),
                ('pase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='seguridad.paseingreso')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to='seguridad.puestoseguridad')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_hora',),
            },
        ),
        migrations.CreateModel(
            name='TurnoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('patron', models.CharField(default='24x72', editable=False, max_length=20)),
                ('relevo_realizado', models.BooleanField(default=False)),
                ('novedades', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='seguridad.guardia')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='seguridad.puestoseguridad')),
            ],
            options={
                'verbose_name': 'Turno de guardia',
                'verbose_name_plural': 'Turnos de guardia',
                'ordering': ('-inicio',),
            },
        ),
        migrations.CreateModel(
            name='RondaSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('galpon', models.CharField(max_length=120)),
                ('puntos_verificados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('completada', 'Completada'), ('con_novedad', 'Con novedad')], default='iniciada', max_length=15)),
                ('hallazgos', models.TextField(blank=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas', to='seguridad.turnoguardia')),
            ],
        ),
    ]
