# Generated by Django 6.0.4 on 2026-05-06 22:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento por defecto para esta categoría', max_digits=5)),
            ],
            options={
                'verbose_name': 'Categoría de Cliente',
                'verbose_name_plural': 'Categorías de Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('V', 'Venezolano (V)'), ('E', 'Extranjero (E)'), ('J', 'Jurídico (J)'), ('G', 'Gubernamental (G)'), ('P', 'Pasaporte (P)')], default='V', max_length=1, verbose_name='Tipo Doc.')),
                ('rif', models.CharField(help_text='Ejemplo: J123456789 (Sin guiones, incluir letra inicial)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Use RIF o cedula venezolana con letra inicial. Ej: J-12345678-9 o V-12345678.', regex='^[VEJGP]-?\\d{7,9}-?\\d?$')], verbose_name='RIF / Cédula')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('empresa', 'Empresa')], default='empresa', max_length=20)),
                ('tipo_contribuyente', models.CharField(choices=[('ordinario', 'Contribuyente ordinario IVA'), ('formal', 'Contribuyente formal'), ('especial', 'Sujeto pasivo especial'), ('no_contribuyente', 'No contribuyente')], default='ordinario', max_length=20, verbose_name='Tipo de contribuyente')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('telefono2', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(default='Venezuela', max_length=100)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sin límite', max_digits=14)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='ventas.categoriacliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Cliente',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Pedido')], default='borrador', max_length=12)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('terminos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ventas.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_despacho', models.DateField()),
                ('transportista', models.CharField(blank=True, max_length=200)),
                ('numero_guia', models.CharField(blank=True, max_length=100)),
                ('numero_control', models.CharField(blank=True, max_length=50, verbose_name='Nro. de control fiscal')),
                ('rif_transportista', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Use RIF o cedula venezolana con letra inicial. Ej: J-12345678-9 o V-12345678.', regex='^[VEJGP]-?\\d{7,9}-?\\d?$')])),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20)),
                ('conductor_nombre', models.CharField(blank=True, max_length=150)),
                ('conductor_cedula', models.CharField(blank=True, max_length=20)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sin_derecho_credito_fiscal', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('despachado', 'Despachado'), ('entregado', 'Entregado')], default='preparando', max_length=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('despachado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_despacho'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_despachada', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observacion', models.CharField(blank=True, max_length=300)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.despacho')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='ventas.detallepedido')),
            ],
            options={
                'verbose_name': 'Detalle de Despacho',
                'verbose_name_plural': 'Detalles de Despacho',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('facturado', 'Facturado'), ('anulado', 'Anulado')], default='borrador', max_length=15)),
                ('direccion_entrega', models.TextField(blank=True)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('impuesto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ventas.cliente')),
                ('cotizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='ventas.cotizacion')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='ventas.pedido'),
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('litro', 'Litro'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('docena', 'Docena'), ('metro', 'Metro')], default='unidad', max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_minimo', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Precio mínimo permitido con descuento', max_digits=12)),
                ('impuesto_pct', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA %')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ventas.categoriaproductoventa')),
                ('producto_base', models.ForeignKey(blank=True, help_text='Vincular con el producto fabricado para control de stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_venta', to='produccion.productoterminado')),
            ],
            options={
                'verbose_name': 'Producto de Venta',
                'verbose_name_plural': 'Productos de Venta',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='ventas.productoventa'),
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='ventas.productoventa')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
    ]
