# Generated by Django 6.0.6 on 2026-07-03 19:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacliente',
            options={'verbose_name': 'Categoría de Cliente', 'verbose_name_plural': 'Categorías de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproductoventa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactocliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalledespacho',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido', '-creado_en'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='productoventa',
            options={},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='direccion_entrega',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='categoriaproductoventa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='descuento_pct',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dias_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono2',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_contribuyente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='descuento_pct',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='impuesto_pct',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='terminos',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='conductor_cedula',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='conductor_nombre',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='numero_control',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='numero_guia',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='peso_total_kg',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='placa_vehiculo',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='rif_transportista',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='sin_derecho_credito_fiscal',
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='transportista',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='descripcion',
        ),
        migrations.AlterUniqueTogether(
            name='detallepedido',
            unique_together={('pedido', 'producto')},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descuento_pct',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='impuesto_pct',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='precio_minimo',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='producto_base',
        ),
        migrations.RemoveField(
            model_name='productoventa',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_global_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Desc. Global (%)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_despacho',
            field=models.TextField(blank=True, verbose_name='Dirección de Despacho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='moneda',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='producto_base_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='categoriacliente',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(max_length=20, unique=True, verbose_name='RIF/Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(default='juridico', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='impuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='despachado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='fecha_despacho',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pedido'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.cotizacion'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.productoventa'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='cantidad_despachada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='detalle_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.detallepedido'),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_despachada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_pedidos', to='ventas.productoventa'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='base_imponible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='impuesto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.categoriaproductoventa'),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='impuesto_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='productoventa',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='descripcion',
        ),
    ]
