# Generated by Django 6.0.8 on 2026-09-12 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_seed_produccion_textil'),
        ('ventas', '0003_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='orden_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='produccion.ordenproduccion'),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='colores',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='composicion_textil',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='es_sobre_pedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoventa',
            name='tallas',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
