# Generated by Django 6.0.3 on 2026-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_seed_categorias_productos_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida')], default='borrador', max_length=20),
        ),
    ]
