# Generated by Django 6.0.3 on 2026-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='moneda',
            field=models.CharField(choices=[('VES', 'Bolívares (VES)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='USD', max_length=3, verbose_name='Moneda'),
        ),
    ]
